### ISSUE TITLE
Warnings after upgrading to React 16.9: componentWillMount and componentWillReceiveProps renamed

### ISSUE THREAD

**Issue by bouwe77** [linsight/react-keyboard-event-handler#15]
After upgrading to React 16.9.0 I get the following two warnings:

```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
```

and

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
```

The warning suggests to rename these methods to *_UNSAFE, but this is a workaround and I can imagine you might want a better solution?

**Comment by dlin-me** [comment]
Thanks. I will start working on a new version for it.

**Comment by hifalutin** [comment]
Thanks @dlin-me! It's a great package!

**Comment by trebor** [comment]
any word on this.  my log is now swamped with warnings. :\

**Comment by dlin-me** [comment]
v1.5.2 addressed these warnings.
