### ISSUE TITLE
down and up keys control the scrollbar on chrome

### ISSUE THREAD

**Issue by shaheen-karodia** [linsight/react-keyboard-event-handler#21]
Love this library. I have a page that has long enough content to cause the scrollbar to appear on the browser. I have used your library to assign functionality to the up and down arrows. This functionality works but browser window still scrolls. is there any way to prevent the browser window from scrolling?

**Comment by dlin-me** [comment]
you can try  `e.preventDefault();` in your `onKeyEvent` prop:
 

`<KeyboardEventHandler
    handleKeys={['up', 'down']}
    onKeyEvent={(key, e) => {
                     console.log(`do something upon keydown event of ${key}`);
                     e.preventDefault();
} />`

**Comment by shaheen-karodia** [comment]
thank you very much, that worked.
