### ISSUE TITLE
handleKeys 'numeric' doesn't include numpad numbers on Windows.

### ISSUE THREAD

**Issue by fastmover** [linsight/react-keyboard-event-handler#3]

**Comment by dlin-me** [comment]
Added support in 1.3.2

**Comment by kishorenaib** [comment]
I just updated to 1.3.2, numpad still does not function for me.  Top row numbers work, but numpad does not send a value.  Using Ubuntu.
Code:
`	<KeyboardEventHandler handleKeys={['1', '2', '3','4','5','6','7','8']} onKeyEvent={(key, e) =>
							this.handleOptionKeyPress2(key)
}
`

**Comment by fastmover** [comment]
yeah the issue being it's checking keyCode 48-57 which is the number keys at the top of the keyboard, the numpad keys are 96-105, reference table in top right of page: https://keycode.info/

**Comment by dlin-me** [comment]
@kishorenaib  Are you sure you you have the new version ? could you try the demo page ? https://linsight.github.io/react-keyboard-event-handler/demo/dist/index.html

**Comment by fastmover** [comment]
Sweet! Thanks for the quick fix!

**Comment by dlin-me** [comment]
No worries. Closing as resolved.
