### ISSUE TITLE
Document how to test keyboard events?

### ISSUE THREAD

**Issue by ronen** [linsight/react-keyboard-event-handler#5]
Thanks for the super-handy component!

It took me a while to figure out how to test keyboard events when using [jsdom](https://github.com/jsdom/jsdom). Maybe you'd want to add a section on testing to the README?  

FYI see https://github.com/jsdom/jsdom/issues/1634#issuecomment-436703999.

**Comment by dlin-me** [comment]
Hi @ronen , for test, I use [simulate-event](https://www.npmjs.com/package/simulate-event) to simulate keyboard events. It works well for my case. 

Testing with jsdom is outside of the scope of this react component.
