### ISSUE TITLE
Attempting to call a function that passes in variable

### ISSUE THREAD

**Issue by elarue53078** [linsight/react-keyboard-event-handler#7]
I am attempting to use the KeyboardEventHandler to modify the valueSelected prop of my component, but when I pass in the variable I'm using to set this prop, it mutates the variable into a function.

Here are the relevant lines of code:

valueSelected={selectedServerType}

<KeyboardEventHandler
          handleKeys={['left', 'right']}
          onKeyEvent={
            (selectedServerType = key =>
              this.handleKeyPress(key, selectedServerType))
          }
        />

When selectedServerType first gets passed into handleKeyPress, and I console.log the value, it returns 'function selectedServerType()'

How can I pass the variable into handleKeyPress without it being mutated into a function?

**Comment by elarue53078** [comment]
Thanks!  That helped to prevent the variable from being mutated into a function.  But now I still don't have the end goal of updating the value of selectedServerType in render so that valueSelected gets updated when handleKeyPress is run.

**Comment by dlin-me** [comment]
👍
