### ISSUE TITLE
KeyboardEventHandler not calling function in test

### ISSUE THREAD

**Issue by elarue53078** [linsight/react-keyboard-event-handler#8]
Cross-posted with issue #5 (closed)

I'm trying to test a keyboard event. Here is the text of my test:

it('triggers change in environment with arrow keys', () => {
wrapper.find('t').simulate('keydown', { keyCode: 39 });
expect(defaultProps.setServerTypeHandler).toHaveBeenCalledWith('dedicated');
});

In this case, the function that contains the call to setServerTypeHandler, which is the function that gets called on the keyboard event, is not getting called in the test - I have checked this in the test coverage, and neither the onKeyEvent nor the function, handleKeyPress, are covered. Is there a reason for this?

**Comment by dlin-me** [comment]
Hi, thanks for reporting.

Now I understand what the problem was. I will have a look how to get it work with Enzyme.

Meanwhile, I find this discussion is helpful: https://github.com/airbnb/enzyme/issues/441

You might want to try specifying all 'key', 'keyCode' and 'which' in the simulated event.
```
wrapper.find('.myclass').simulate('keyDown', { key: 'Tab', keyCode: 9, which: 9 });
```

**Comment by dlin-me** [comment]
Unfortunately, there's no good way for testing keyboard events with Enzyme when using this react component.

Enzyme has two main limitations (ref: https://github.com/airbnb/enzyme/blob/master/docs/future.md):

1. Event simulation is limited for Shallow rendering. But this component needs `componentWillMount` for registering keyboard events;

2. Event propagation is not supported. However, Key events on wrapped components are bubbled up and handled by at the document level by this component.

Therefore:
1. When testing  key events, we can only simulate events directly fired from `document.body`;
1. There's no good way for testing/simulating key events from wrapped child component

**Comment by dlin-me** [comment]
Updated Readme for testing. Closing this now.
